export const scales = {
  pentatonic: {
    name: "Pentatonica Maggiore",
    notes: ["C4", "D4", "E4", "G4", "A4", "C5", "D5", "E5", "G5", "A5"],
    description:
      "Scala pentatonica maggiore estesa - suono piacevole e armonioso",
  },
  major: {
    name: "Maggiore",
    notes: [
      "C4",
      "D4",
      "E4",
      "F4",
      "G4",
      "A4",
      "B4",
      "C5",
      "D5",
      "E5",
      "F5",
      "G5",
      "A5",
      "B5",
    ],
    description: "Scala maggiore estesa - suono brillante e allegro",
  },
  minor: {
    name: "Minore",
    notes: [
      "C4",
      "D4",
      "Eb4",
      "F4",
      "G4",
      "Ab4",
      "Bb4",
      "C5",
      "D5",
      "Eb5",
      "F5",
      "G5",
      "Ab5",
      "Bb5",
    ],
    description: "Scala minore estesa - suono malinconico e profondo",
  },
  blues: {
    name: "Blues",
    notes: [
      "C4",
      "Eb4",
      "F4",
      "Gb4",
      "G4",
      "Bb4",
      "C5",
      "Eb5",
      "F5",
      "Gb5",
      "G5",
      "Bb5",
    ],
    description: "Scala blues estesa - suono soul e blues",
  },
  dorian: {
    name: "Dorico",
    notes: [
      "C4",
      "D4",
      "Eb4",
      "F4",
      "G4",
      "A4",
      "Bb4",
      "C5",
      "D5",
      "Eb5",
      "F5",
      "G5",
      "A5",
      "Bb5",
    ],
    description: "Modo dorico - suono jazz e fusion",
  },
  phrygian: {
    name: "Frigio",
    notes: [
      "C4",
      "Db4",
      "Eb4",
      "F4",
      "G4",
      "Ab4",
      "Bb4",
      "C5",
      "Db5",
      "Eb5",
      "F5",
      "G5",
      "Ab5",
      "Bb5",
    ],
    description: "Modo frigio - suono esotico e misterioso",
  },
  lydian: {
    name: "Lidio",
    notes: [
      "C4",
      "D4",
      "E4",
      "F#4",
      "G4",
      "A4",
      "B4",
      "C5",
      "D5",
      "E5",
      "F#5",
      "G5",
      "A5",
      "B5",
    ],
    description: "Modo lidio - suono sognante e fluttuante",
  },
  mixolydian: {
    name: "Misolidio",
    notes: [
      "C4",
      "D4",
      "E4",
      "F4",
      "G4",
      "A4",
      "Bb4",
      "C5",
      "D5",
      "E5",
      "F5",
      "G5",
      "A5",
      "Bb5",
    ],
    description: "Modo misolidio - suono rock e blues",
  },
  locrian: {
    name: "Locrio",
    notes: [
      "C4",
      "Db4",
      "Eb4",
      "F4",
      "Gb4",
      "Ab4",
      "Bb4",
      "C5",
      "Db5",
      "Eb5",
      "F5",
      "Gb5",
      "Ab5",
      "Bb5",
    ],
    description: "Modo locrio - suono dissonante e instabile",
  },
  harmonic: {
    name: "Minore Armonica",
    notes: [
      "C4",
      "D4",
      "Eb4",
      "F4",
      "G4",
      "Ab4",
      "B4",
      "C5",
      "D5",
      "Eb5",
      "F5",
      "G5",
      "Ab5",
      "B5",
    ],
    description: "Scala minore armonica - suono mediorientale e drammatico",
  },
  melodic: {
    name: "Minore Melodica",
    notes: [
      "C4",
      "D4",
      "Eb4",
      "F4",
      "G4",
      "A4",
      "B4",
      "C5",
      "D5",
      "Eb5",
      "F5",
      "G5",
      "A5",
      "B5",
    ],
    description: "Scala minore melodica - suono jazz e classico",
  },
};
